export const citiesData = [
    {key: 'Metro Manila', label: 'Caloocan',value: 'Caloocan'},
    {key: 'Metro Manila', label: 'Las Piñas', value: 'Las Piñas' },
    {key: 'Metro Manila', label: 'Makati', value: 'Makati' },
    {key: 'Metro Manila', label: 'Malabon', value: 'Malabon' },
    {key: 'Metro Manila', label: 'Mandaluyong',value: 'Mandaluyong' },
    {key: 'Metro Manila', label: 'Manila', value: 'Manila' },
    {key: 'Metro Manila', label: 'Marikina', value: 'Marikina' },
    {key: 'Metro Manila', label: 'Muntinlupa', value: 'Muntinlupa' },
    {key: 'Metro Manila', label: 'Navotas',value: 'Navotas' },
    {key: 'Metro Manila', label: 'Parañaque', value: 'Parañaque' },
    {key: 'Metro Manila', label: 'Pasay', value: 'Pasay' },
    {key: 'Metro Manila', label: 'Pasig', value: 'Pasig' },
    {key: 'Metro Manila', label: 'Pateros',value: 'Pateros' },
    {key: 'Metro Manila', label: 'Quezon City', value: 'Quezon City' },
    {key: 'Metro Manila', label: 'San Juan', value: 'San Juan' },
    {key: 'Metro Manila', label: 'Taguig', value: 'Taguig' },
    {key: 'Metro Manila', label: 'Valenzuela', value: 'Valenzuela' },
    {key: 'Cebu', label: 'Alcantara', value: 'Alcantara' },
    {key: 'Cebu', label: 'Alcoy', value: 'Alcoy' },
    {key: 'Cebu', label: 'Alegria', value: 'Alegria' },
    {key: 'Cebu', label: 'Aloguinsan', value: 'Aloguinsan' },
    {key: 'Cebu', label: 'Argao', value: 'Argao' },
    {key: 'Cebu', label: 'Asturias', value: 'Asturias' },
    {key: 'Cebu', label: 'Badian', value: 'Badian' },
    {key: 'Cebu', label: 'Balamban', value: 'Balamban' },
    {key: 'Cebu', label: 'Bantayan', value: 'Bantayan' },
    {key: 'Cebu', label: 'Barili', value: 'Barili' },
    {key: 'Cebu', label: 'Bogo', value: 'Bogo' },
    {key: 'Cebu', label: 'Boljoon', value: 'Boljoon' },
    {key: 'Cebu', label: 'Borbon', value: 'Borbon' },
    {key: 'Cebu', label: 'Carcar', value: 'Carcar' },
    {key: 'Cebu', label: 'Carmen', value: 'Carmen' },
    {key: 'Cebu', label: 'Catmon', value: 'Catmon' },
    {key: 'Cebu', label: 'Cebu City', value: 'Cebu City' },
    {key: 'Cebu', label: 'Compostela', value: 'Compostela' },
    {key: 'Cebu', label: 'Consolacion', value: 'Consolacion' },
    {key: 'Cebu', label: 'Cordova', value: 'Cordova' },
    {key: 'Cebu', label: 'Daanbantayan', value: 'Daanbantayan' },
    {key: 'Cebu', label: 'Dalaguete', value: 'Dalaguete' },
    {key: 'Cebu', label: 'Danao', value: 'Danao' },
    {key: 'Cebu', label: 'Dumanjug', value: 'Dumanjug' },
    {key: 'Cebu', label: 'Ginatilan', value: 'Ginatilan' },
    {key: 'Cebu', label: 'Lapu-Lapu', value: 'Lapu-Lapu' },
    {key: 'Cebu', label: 'Liloan', value: 'Liloan' },
    {key: 'Cebu', label: 'Madridejos', value: 'Madridejos' },
    {key: 'Cebu', label: 'Malabuyoc', value: 'Malabuyoc' },
    {key: 'Cebu', label: 'Mandaue', value: 'Mandaue' },
    {key: 'Cebu', label: 'Medellin', value: 'Medellin' },
    {key: 'Cebu', label: 'Minglanilla', value: 'Minglanilla' },
    {key: 'Cebu', label: 'Moalboal', value: 'Moalboal' },
    {key: 'Cebu', label: 'Naga', value: 'Naga' },
    {key: 'Cebu', label: 'Oslob', value: 'Oslob' },
    {key: 'Cebu', label: 'Pilar', value: 'Pilar' },
    {key: 'Cebu', label: 'Pinamungajan', value: 'Pinamungajan' },
    {key: 'Cebu', label: 'Poro', value: 'Poro' },
    {key: 'Cebu', label: 'Ronda', value: 'Ronda' },
    {key: 'Cebu', label: 'Samboan', value: 'Samboan' },
    {key: 'Cebu', label: 'San Fernando', value: 'San Fernando' },
    {key: 'Cebu', label: 'San Francisco', value: 'San Francisco' },
    {key: 'Cebu', label: 'San Remigio', value: 'San Remigio' },
    {key: 'Cebu', label: 'Santa Fe', value: 'Santa Fe' },
    {key: 'Cebu', label: 'Santander', value: 'Santander' },
    {key: 'Cebu', label: 'Sibonga', value: 'Sibonga' },
    {key: 'Cebu', label: 'Sogod', value: 'Sogod' },
    {key: 'Cebu', label: 'Tabogon', value: 'Tabogon' },
    {key: 'Cebu', label: 'Tabuelan', value: 'Tabuelan' },
    {key: 'Cebu', label: 'Talisay', value: 'Talisay' },
    {key: 'Cebu', label: 'Toledo', value: 'Toledo' },
    {key: 'Cebu', label: 'Tuburan', value: 'Tuburan' },
    {key: 'Cebu', label: 'Tudela', value: 'Tudela' },
    {key: 'Davao del Norte', label: 'Asuncion', value: 'Asuncion' },
    {key: 'Davao del Norte', label: 'Braulio E. Dujali', value: 'Braulio E. Dujali' },
    {key: 'Davao del Norte', label: 'Carmen', value: 'Carmen' },
    {key: 'Davao del Norte', label: 'Kapalong', value: 'Kapalong' },
    {key: 'Davao del Norte', label: 'New Corella', value: 'New Corella' },
    {key: 'Davao del Norte', label: 'Panabo', value: 'Panabo' },
    {key: 'Davao del Norte', label: 'Samal', value: 'Samal' },
    {key: 'Davao del Norte', label: 'San Isidro', value: 'San Isidro' },
    {key: 'Davao del Norte', label: 'Santo Tomas', value: 'Santo Tomas' },
    {key: 'Davao del Norte', label: 'Tagum', value: 'Tagum' },
    {key: 'Davao del Norte', label: 'Talaingod', value: 'Talaingod' },
    {key: 'Davao del Sur', label: 'Bansalan', value: 'Bansalan' },
    {key: 'Davao del Sur', label: 'Davao City', value: 'Davao City' },
    {key: 'Davao del Sur', label: 'Digos', value: 'Digos' },
    {key: 'Davao del Sur', label: 'Hagonoy', value: 'Hagonoy' },
    {key: 'Davao del Sur', label: 'Kiblawan', value: 'Kiblawan' },
    {key: 'Davao del Sur', label: 'Magsaysay', value: 'Magsaysay' },
    {key: 'Davao del Sur', label: 'Malalag', value: 'Malalag' },
    {key: 'Davao del Sur', label: 'Matanao', value: 'Matanao' },
    {key: 'Davao del Sur', label: 'Padada', value: 'Padada' },
    {key: 'Davao del Sur', label: 'Santa Cruz', value: 'Santa Cruz' },
    {key: 'Davao del Sur', label: 'Sulop', value: 'Sulop' },
    {key: 'Davao Oriental', label: 'Baganga', value: 'Baganga' },
    {key: 'Davao Oriental', label: 'Banaybanay', value: 'Banaybanay' },
    {key: 'Davao Oriental', label: 'Boston', value: 'Boston' },
    {key: 'Davao Oriental', label: 'Caraga', value: 'Caraga' },
    {key: 'Davao Oriental', label: 'Cateel', value: 'Cateel' },
    {key: 'Davao Oriental', label: 'Governor Generoso', value: 'Governor Generoso' },
    {key: 'Davao Oriental', label: 'Lupon', value: 'Lupon' },
    {key: 'Davao Oriental', label: 'Manay', value: 'Manay' },
    {key: 'Davao Oriental', label: 'Mati', value: 'Mati' },
    {key: 'Davao Oriental', label: 'San Isidro', value: 'San Isidro' },
    {key: 'Davao Oriental', label: 'Tarragona', value: 'Tarragona' },
    {key: 'Abra', label: 'Bangued', value: 'Bangued' },
    {key: 'Abra', label: 'Boliney', value: 'Boliney' },
    {key: 'Abra', label: 'Bucay', value: 'Bucay' },
    {key: 'Abra', label: 'Bucloc', value: 'Bucloc' },
    {key: 'Abra', label: 'Daguioman', value: 'Daguioman' },
    {key: 'Abra', label: 'Danglas', value: 'Danglas' },
    {key: 'Abra', label: 'Dolores', value: 'Dolores' },
    {key: 'Abra', label: 'La Paz', value: 'La Paz' },
    {key: 'Abra', label: 'Lacub', value: 'Lacub' },
    {key: 'Abra', label: 'Lagangilang', value: 'Lagangilang' },
    {key: 'Abra', label: 'Lagayan', value: 'Lagayan' },
    {key: 'Abra', label: 'Langiden', value: 'Langiden' },
    {key: 'Abra', label: 'Licuan-Baay', value: 'Licuan-Baay' },
    {key: 'Abra', label: 'Luba', value: 'Luba' },
    {key: 'Abra', label: 'Malibcong', value: 'Malibcong' },
    {key: 'Abra', label: 'Manabo', value: 'Manabo' },
    {key: 'Abra', label: 'Peñarrubia', value: 'Peñarrubia' },
    {key: 'Abra', label: 'Pidigan', value: 'Pidigan' },
    {key: 'Abra', label: 'Pilar', value: 'Pilar' },
    {key: 'Abra', label: 'Sallapadan', value: 'Sallapadan' },
    {key: 'Abra', label: 'San Isidro', value: 'San Isidro' },
    {key: 'Abra', label: 'San Juan', value: 'San Juan' },
    {key: 'Abra', label: 'San Quintin', value: 'San Quintin' },
    {key: 'Abra', label: 'Tayum', value: 'Tayum' },
    {key: 'Abra', label: 'Tineg', value: 'Tineg' },
    {key: 'Abra', label: 'Tubo', value: 'Tubo' },
    {key: 'Abra', label: 'Villaviciosa', value: 'Villaviciosa' },
    {key: 'Agusan del Norte', label: 'Buenavista', value: 'Buenavista' },
    {key: 'Agusan del Norte', label: 'Butuan', value: 'Butuan' },
    {key: 'Agusan del Norte', label: 'Cabadbaran', value: 'Cabadbaran' },
    {key: 'Agusan del Norte', label: 'Carmen', value: 'Carmen' },
    {key: 'Agusan del Norte', label: 'Jabonga', value: 'Jabonga' },
    {key: 'Agusan del Norte', label: 'Kitcharao', value: 'Kitcharao' },
    {key: 'Agusan del Norte', label: 'Las Nieves', value: 'Las Nieves' },
    {key: 'Agusan del Norte', label: 'Magallanes', value: 'Magallanes' },
    {key: 'Agusan del Norte', label: 'Nasipit', value: 'Nasipit' },
    {key: 'Agusan del Norte', label: 'Remedios T. Romualdez', value: 'Remedios T. Romualdez' },
    {key: 'Agusan del Norte', label: 'Santiago', value: 'Santiago' },
    {key: 'Agusan del Norte', label: 'Tubay', value: 'Tubay' },
    {key: 'Agusan del Sur', label: 'Bayugan', value: 'Bayugan' },
    {key: 'Agusan del Sur', label: 'Bunawan', value: 'Bunawan' },
    {key: 'Agusan del Sur', label: 'Esperanza', value: 'Esperanza' },
    {key: 'Agusan del Sur', label: 'La Paz', value: 'La Paz' },
    {key: 'Agusan del Sur', label: 'Loreto', value: 'Loreto' },
    {key: 'Agusan del Sur', label: 'Prosperidad', value: 'Prosperidad' },
    {key: 'Agusan del Sur', label: 'Rosario', value: 'Rosario' },
    {key: 'Agusan del Sur', label: 'San Francisco', value: 'San Francisco' },
    {key: 'Agusan del Sur', label: 'San Luis', value: 'San Luis' },
    {key: 'Agusan del Sur', label: 'Santa Josefa', value: 'Santa Josefa' },
    {key: 'Agusan del Sur', label: 'Sibagat', value: 'Sibagat' },
    {key: 'Agusan del Sur', label: 'Talacogon', value: 'Talacogon' },
    {key: 'Agusan del Sur', label: 'Trento', value: 'Trento' },
    {key: 'Agusan del Sur', label: 'Veruela', value: 'Veruela' },
    {key: 'Aklan', label: 'Altavas', value: 'Altavas' },
    {key: 'Aklan',  label: 'Balete', value: 'Balete' },
    {key: 'Aklan',  label: 'Banga', value: 'Banga' },
    {key: 'Aklan',  label: 'Batan', value: 'Batan' },
    {key: 'Aklan',  label: 'Buruanga', value: 'Buruanga' },
    {key: 'Aklan',  label: 'Ibajay', value: 'Ibajay' },
    {key: 'Aklan',  label: 'Kalibo', value: 'Kalibo' },
    {key: 'Aklan',  label: 'Lezo', value: 'Lezo' },
    {key: 'Aklan',  label: 'Libacao', value: 'Libacao' },
    {key: 'Aklan',  label: 'Madalag', value: 'Madalag' },
    {key: 'Aklan',  label: 'Makato', value: 'Makato' },
    {key: 'Aklan',  label: 'Malay', value: 'Malay' },
    {key: 'Aklan',  label: 'Malinao', value: 'Malinao' },
    {key: 'Aklan',  label: 'Nabas', value: 'Nabas' },
    {key: 'Aklan',  label: 'New Washington', value: 'New Washington' },
    {key: 'Aklan',  label: 'Numancia', value: 'Numancia' },
    {key: 'Aklan',  label: 'Tangalan', value: 'Tangalan' },
    {key: 'Albay', label: 'Bacacay', value: 'Bacacay' },
    {key: 'Albay', label: 'Camalig', value: 'Camalig' },
    {key: 'Albay', label: 'Daraga', value: 'Daraga' },
    {key: 'Albay', label: 'Guinobatan', value: 'Guinobatan' },
    {key: 'Albay', label: 'Jovellar', value: 'Jovellar' },
    {key: 'Albay', label: 'Legazpi', value: 'Legazpi' },
    {key: 'Albay', label: 'Libon', value: 'Libon' },
    {key: 'Albay', label: 'Ligao', value: 'Ligao' },
    {key: 'Albay', label: 'Malilipot', value: 'Malilipot' },
    {key: 'Albay', label: 'Malinao', value: 'Malinao' },
    {key: 'Albay', label: 'Manito', value: 'Manito' },
    {key: 'Albay', label: 'Oas', value: 'Oas' },
    {key: 'Albay', label: 'Pio Duran', value: 'Pio Duran' },
    {key: 'Albay', label: 'Polangui', value: 'Polangui' },
    {key: 'Albay', label: 'Rapu-Rapu', value: 'Rapu-Rapu' },
    {key: 'Albay', label: 'Santo Domingo', value: 'Santo Domingo' },
    {key: 'Albay', label: 'Tabaco', value: 'Tabaco' },
    {key: 'Albay', label: 'Tiwi', value: 'Tiwi' },
    {key: 'Antique', label: 'Anini-y', value: 'Anini-y' },
    {key: 'Antique', label: 'Barbaza', value: 'Barbaza' },
    {key: 'Antique', label: 'Belison', value: 'Belison' },
    {key: 'Antique', label: 'Bugasong', value: 'Bugasong' },
    {key: 'Antique', label: 'Caluya', value: 'Caluya' },
    {key: 'Antique', label: 'Culasi', value: 'Culasi' },
    {key: 'Antique', label: 'Hamtic', value: 'Hamtic' },
    {key: 'Antique', label: 'Laua-an', value: 'Laua-an' },
    {key: 'Antique', label: 'Libertad', value: 'Libertad' },
    {key: 'Antique', label: 'Pandan', value: 'Pandan' },
    {key: 'Antique', label: 'Patnongon', value: 'Patnongon' },
    {key: 'Antique', label: 'San Jose de Buenavista', value: 'San Jose de Buenavista' },
    {key: 'Antique', label: 'San Remigio', value: 'San Remigio' },
    {key: 'Antique', label: 'Sebaste', value: 'Sebaste' },
    {key: 'Antique', label: 'Sibalom', value: 'Sibalom' },
    {key: 'Antique', label: 'Tibiao', value: 'Tibiao' },
    {key: 'Antique', label: 'Tobias Fornier', value: 'Tobias Fornier' },
    {key: 'Antique', label: 'Valderrama', value: 'Valderrama' },
    {key: 'Apayao', label: 'Calanasan', value: 'Calanasan' },
    {key: 'Apayao', label: 'Conner', value: 'Conner' },
    {key: 'Apayao', label: 'Flora', value: 'Flora' },
    {key: 'Apayao', label: 'Kabugao', value: 'Kabugao' },
    {key: 'Apayao', label: 'Luna', value: 'Luna' },
    {key: 'Apayao', label: 'Pudtol', value: 'Pudtol' },
    {key: 'Apayao', label: 'Santa Marcela', value: 'Santa Marcela' },
    {key: 'Aurora', label: 'Baler', value: 'Baler' },
    {key: 'Aurora', label: 'Casiguran', value: 'Casiguran' },
    {key: 'Aurora', label: 'Dilasag', value: 'Dilasag' },
    {key: 'Aurora', label: 'Dinalungan', value: 'Dinalungan' },
    {key: 'Aurora', label: 'Dingalan', value: 'Dingalan' },
    {key: 'Aurora', label: 'Dipaculao', value: 'Dipaculao' },
    {key: 'Aurora', label: 'Maria Aurora', value: 'Maria Aurora' },
    {key: 'Aurora', label: 'San Luis', value: 'San Luis' },
    {key: 'Basilan', label: 'Akbar', value: 'Akbar' },
    {key: 'Basilan', label: 'Al-Barka', value: 'Al-Barka' },
    {key: 'Basilan', label: 'Hadji Mohammad Ajul', value: 'Hadji Mohammad Ajul' },
    {key: 'Basilan', label: 'Hadji Muhtamad', value: 'Hadji Muhtamad' },
    {key: 'Basilan', label: 'Isabela City', value: 'Isabela City' },
    {key: 'Basilan', label: 'Lamitan', value: 'Lamitan' },
    {key: 'Basilan', label: 'Lantawan', value: 'Lantawan' },
    {key: 'Basilan', label: 'Maluso', value: 'Maluso' },
    {key: 'Basilan', label: 'Sumisip', value: 'Sumisip' },
    {key: 'Basilan', label: 'Tabuan-Lasa', value: 'Tabuan-Lasa' },
    {key: 'Basilan', label: 'Tipo-Tipo', value: 'Tipo-Tipo' },
    {key: 'Basilan', label: 'Tuburan', value: 'Tuburan' },
    {key: 'Basilan', label: 'Ungkaya Pukan', value: 'Ungkaya Pukan' },
    {key: 'Bataan', label: 'Abucay', value: 'Abucay' },
    {key: 'Bataan', label: 'Bagac', value: 'Bagac' },
    {key: 'Bataan', label: 'Balanga', value: 'Balanga' },
    {key: 'Bataan', label: 'Dinalupihan', value: 'Dinalupihan' },
    {key: 'Bataan', label: 'Hermosa', value: 'Hermosa' },
    {key: 'Bataan', label: 'Limay', value: 'Limay' },
    {key: 'Bataan', label: 'Mariveles', value: 'Mariveles' },
    {key: 'Bataan', label: 'Morong', value: 'Morong' },
    {key: 'Bataan', label: 'Orani', value: 'Orani' },
    {key: 'Bataan', label: 'Orion', value: 'Orion' },
    {key: 'Bataan', label: 'Pilar', value: 'Pilar' },
    {key: 'Bataan', label: 'Samal', value: 'Samal' },
    {key: 'Batanes', label: 'Basco', value: 'Basco' },
    {key: 'Batanes', label: 'Itbayat', value: 'Itbayat' },
    {key: 'Batanes', label: 'Ivana', value: 'Ivana' },
    {key: 'Batanes', label: 'Mahatao', value: 'Mahatao' },
    {key: 'Batanes', label: 'Sabtang', value: 'Sabtang' },
    {key: 'Batanes', label: 'Uyugan', value: 'Uyugan' },
    {key: 'Batangas', label: 'Agoncillo', value: 'Agoncillo' },
    {key: 'Batangas', label: 'Alitagtag', value: 'Alitagtag' },
    {key: 'Batangas', label: 'Balayan', value: 'Balayan' },
    {key: 'Batangas', label: 'Balete', value: 'Balete' },
    {key: 'Batangas', label: 'Batangas City', value: 'Batangas City' },
    {key: 'Batangas', label: 'Bauan', value: 'Bauan' },
    {key: 'Batangas', label: 'Calaca', value: 'Calaca' },
    {key: 'Batangas', label: 'Calatagan', value: 'Calatagan' },
    {key: 'Batangas', label: 'Cuenca', value: 'Cuenca' },
    {key: 'Batangas', label: 'Ibaan', value: 'Ibaan' },
    {key: 'Batangas', label: 'Laurel', value: 'Laurel' },
    {key: 'Batangas', label: 'Lemery', value: 'Lemery' },
    {key: 'Batangas', label: 'Lian', value: 'Lian' },
    {key: 'Batangas', label: 'Lipa', value: 'Lipa' },
    {key: 'Batangas', label: 'Lobo', value: 'Lobo' },
    {key: 'Batangas', label: 'Mabini', value: 'Mabini' },
    {key: 'Batangas', label: 'Malvar', value: 'Malvar' },
    {key: 'Batangas', label: 'Mataas na Kahoy', value: 'Mataas na Kahoy' },
    {key: 'Batangas', label: 'Nasugbu', value: 'Nasugbu' },
    {key: 'Batangas', label: 'Padre Garcia', value: 'Padre Garcia' },
    {key: 'Batangas', label: 'Rosario', value: 'Rosario' },
    {key: 'Batangas', label: 'San Jose', value: 'San Jose' },
    {key: 'Batangas', label: 'San Juan', value: 'San Juan' },
    {key: 'Batangas', label: 'San Luis', value: 'San Luis' },
    {key: 'Batangas', label: 'San Nicolas', value: 'San Nicolas' },
    {key: 'Batangas', label: 'San Pascual', value: 'San Pascual' },
    {key: 'Batangas', label: 'Santa Teresita', value: 'Santa Teresita' },
    {key: 'Batangas', label: 'Santo Tomas', value: 'Santo Tomas' },
    {key: 'Batangas', label: 'Taal', value: 'Taal' },
    {key: 'Batangas', label: 'Talisay', value: 'Talisay' },
    {key: 'Batangas', label: 'Tanauan', value: 'Tanauan' },
    {key: 'Batangas', label: 'Taysan', value: 'Taysan' },
    {key: 'Batangas', label: 'Tingloy', value: 'Tingloy' },
    {key: 'Batangas', label: 'Tuy', value: 'Tuy' },
    {key: 'Benguet', label: 'Atok', value: 'Atok' },
    {key: 'Benguet', label: 'Baguio', value: 'Baguio' },
    {key: 'Benguet', label: 'Bakun', value: 'Bakun' },
    {key: 'Benguet', label: 'Bokod', value: 'Bokod' },
    {key: 'Benguet', label: 'Buguias', value: 'Buguias' },
    {key: 'Benguet', label: 'Itogon', value: 'Itogon' },
    {key: 'Benguet', label: 'Kabayan', value: 'Kabayan' },
    {key: 'Benguet', label: 'Kapangan', value: 'Kapangan' },
    {key: 'Benguet', label: 'Kibungan', value: 'Kibungan' },
    {key: 'Benguet', label: 'La Trinidad', value: 'La Trinidad' },
    {key: 'Benguet', label: 'Mankayan', value: 'Mankayan' },
    {key: 'Benguet', label: 'Sablan', value: 'Sablan' },
    {key: 'Benguet', label: 'Tuba', value: 'Tuba' },
    {key: 'Benguet', label: 'Tublay', value: 'Tublay' },
    {key: 'Biliran', label: 'Almeria', value: 'Almeria' },
    {key: 'Biliran', label: 'Biliran', value: 'Biliran' },
    {key: 'Biliran', label: 'Cabucgayan', value: 'Cabucgayan' },
    {key: 'Biliran', label: 'Caibiran', value: 'Caibiran' },
    {key: 'Biliran', label: 'Culaba', value: 'Culaba' },
    {key: 'Biliran', label: 'Kawayan', value: 'Kawayan' },
    {key: 'Biliran', label: 'Maripipi', value: 'Maripipi' },
    {key: 'Biliran', label: 'Naval', value: 'Naval' },
    {key: 'Bohol', label: 'Alicia', value: 'Alicia' },
    {key: 'Bohol', label: 'Anda', value: 'Anda' },
    {key: 'Bohol', label: 'Batuan', value: 'Batuan' },
    {key: 'Bohol', label: 'Bilar', value: 'Bilar' },
    {key: 'Bohol', label: 'Candijay', value: 'Candijay' },
    {key: 'Bohol', label: 'Carmen', value: 'Carmen' },
    {key: 'Bohol', label: 'Dimiao', value: 'Dimiao' },
    {key: 'Bohol', label: 'Duero', value: 'Duero' },
    {key: 'Bohol', label: 'Garcia Hernandez', value: 'Garcia Hernandez' },
    {key: 'Bohol', label: 'Guindulman', value: 'Guindulman' },
    {key: 'Bohol', label: 'Jagna', value: 'Jagna' },
    {key: 'Bohol', label: 'Sevilla', value: 'Sevilla' },
    {key: 'Bohol', label: 'Lila', value: 'Lila' },
    {key: 'Bohol', label: 'Loay', value: 'Loay' },
    {key: 'Bohol', label: 'Loboc', value: 'Loboc' },
    {key: 'Bohol', label: 'Mabini', value: 'Mabini' },
    {key: 'Bohol', label: 'Pilar', value: 'Pilar' },
    {key: 'Bohol', label: 'Sierra Bullones', value: 'Sierra Bullones' },
    {key: 'Bohol', label: 'Valencia', value: 'Valencia' },
    {key: 'Bukidnon', label: 'Baungon', value: 'Baungon' },
    {key: 'Bukidnon', label: 'Cabanglasan', value: 'Cabanglasan' },
    {key: 'Bukidnon', label: 'Damulog', value: 'Damulog' },
    {key: 'Bukidnon', label: 'Dangcagan', value: 'Dangcagan' },
    {key: 'Bukidnon', label: 'Don Carlos', value: 'Don Carlos' },
    {key: 'Bukidnon', label: 'Impasugong', value: 'Impasugong' },
    {key: 'Bukidnon', label: 'Kadingilan', value: 'Kadingilan' },
    {key: 'Bukidnon', label: 'Kalilangan', value: 'Kalilangan' },
    {key: 'Bukidnon', label: 'Kibawe', value: 'Kibawe' },
    {key: 'Bukidnon', label: 'Kitaotao', value: 'Kitaotao' },
    {key: 'Bukidnon', label: 'Lantapan', value: 'Lantapan' },
    {key: 'Bukidnon', label: 'Libona', value: 'Libona' },
    {key: 'Bukidnon', label: 'Malaybalay', value: 'Malaybalay' },
    {key: 'Bukidnon', label: 'Malitbog', value: 'Malitbog' },
    {key: 'Bukidnon', label: 'Manolo Fortich', value: 'Manolo Fortich' },
    {key: 'Bukidnon', label: 'Maramag', value: 'Maramag' },
    {key: 'Bukidnon', label: 'Pangantucan', value: 'Pangantucan' },
    {key: 'Bukidnon', label: 'Quezon', value: 'Quezon' },
    {key: 'Bukidnon', label: 'San Fernando', value: 'San Fernando' },
    {key: 'Bukidnon', label: 'Sumilao', value: 'Sumilao' },
    {key: 'Bukidnon', label: 'Talakag', value: 'Talakag' },
    {key: 'Bukidnon', label: 'Valencia', value: 'Valencia' },
    {key: 'Bulacan', label: 'Angat', value: 'Angat' },
    {key: 'Bulacan', label: 'Balagtas', value: 'Balagtas' },
    {key: 'Bulacan', label: 'Baliuag', value: 'Baliuag' },
    {key: 'Bulacan', label: 'Bocaue', value: 'Bocaue' },
    {key: 'Bulacan', label: 'Bulakan', value: 'Bulakan' },
    {key: 'Bulacan', label: 'Bustos', value: 'Bustos' },
    {key: 'Bulacan', label: 'Calumpit', value: 'Calumpit' },
    {key: 'Bulacan', label: 'Doña Remedios Trinidad', value: 'Doña Remedios Trinidad' },
    {key: 'Bulacan', label: 'Guiguinto', value: 'Guiguinto' },
    {key: 'Bulacan', label: 'Hagonoy', value: 'Hagonoy' },
    {key: 'Bulacan', label: 'Malolos', value: 'Malolos' },
    {key: 'Bulacan', label: 'Marilao', value: 'Marilao' },
    {key: 'Bulacan', label: 'Meycauayan', value: 'Meycauayan' },
    {key: 'Bulacan', label: 'Norzagaray', value: 'Norzagaray' },
    {key: 'Bulacan', label: 'Obando', value: 'Obando' },
    {key: 'Bulacan', label: 'Pandi', value: 'Pandi' },
    {key: 'Bulacan', label: 'Paombong', value: 'Paombong' },
    {key: 'Bulacan', label: 'Plaridel', value: 'Plaridel' },
    {key: 'Bulacan', label: 'Pulilan', value: 'Pulilan' },
    {key: 'Bulacan', label: 'San Ildefonso', value: 'San Ildefonso' },
    {key: 'Bulacan', label: 'San Jose del Monte', value: 'San Jose del Monte' },
    {key: 'Bulacan', label: 'San Miguel', value: 'San Miguel' },
    {key: 'Bulacan', label: 'San Rafael', value: 'San Rafael' },
    {key: 'Bulacan', label: 'Santa Maria', value: 'Santa Maria' }
]