export const iconNames = {
    ADD: 'add-icon',
    APPS: 'apps-icon',
    ARROWDOWN: 'arrow-down-icon',
    ARROWLEFT: 'arrow-left-icon',
    ARROWRIGHT: 'arrow-right-icon',
    ARROWUP: 'arrow-up-icon',
    BELL: 'bell-icon',
    CALENDAR: 'calendar-icon',
    CARD: 'card-icon',
    CHECK: 'check-icon',
    CHEVRONDOWN: 'chevron-down-icon',
    CHEVRONLEFT: 'chevron-left-icon',
    CHEVRONRIGHT:'chevron-right-icon',
    CHEVRONUP: 'chevron-up-icon',
    CLIP: 'clip-icon',
    COPY: 'copy-icon',
    CROSS: 'cross-icon',
    DASHBOARD: 'dashboard-icon',
    DOWNLOAD: 'download-icon',
    EYE: "eye-icon",
    EYEOFF: "eye-off-icon",
    FACEBOOK: 'facebook-icon',
    HAMBURGERMENU: 'hamburger-menu-icon',
    INFORMATION: 'information-icon',
    INSTAGRAM: 'instagram-icon',
    LINK: 'link-icon',
    MAIL: 'mail-icon',
    SEARCH: 'search-icon',
    SHARE: 'share-icon',
    STACKMENU: 'stack-menu-icon',
    SUBTRACT: 'subtract-icon',
    TRANSACTION: 'transaction-icon',
    TRASH: 'trash-icon',
    UPLOAD: 'upload-icon',
    USER: 'user-icon' 
};