export const newProvinces = [
  { label: 'Metro Manila', value: 'Metro Manila',
    cities: [
      { label: 'Caloocan',value: 'Caloocan' },
      { label: 'Las Piñas', value: 'Las Piñas' },
      { label: 'Makati', value: 'Makati' },
      { label: 'Malabon', value: 'Malabon' },
      { label: 'Mandaluyong',value: 'Mandaluyong' },
      { label: 'Manila', value: 'Manila' },
      { label: 'Marikina', value: 'Marikina' },
      { label: 'Muntinlupa', value: 'Muntinlupa' },
      { label: 'Navotas',value: 'Navotas' },
      { label: 'Parañaque', value: 'Parañaque' },
      { label: 'Pasay', value: 'Pasay' },
      { label: 'Pasig', value: 'Pasig' },
      { label: 'Pateros',value: 'Pateros' },
      { label: 'Quezon City', value: 'Quezon City' },
      { label: 'San Juan', value: 'San Juan' },
      { label: 'Taguig', value: 'Taguig' },
      { label: 'Valenzuela', value: 'Valenzuela' },
    ]
  },
  { label: 'Cebu', value: 'Cebu',
    cities: [
      { label: 'Alcantara', value: 'Alcantara' },
      { label: 'Alcoy', value: 'Alcoy' },
      { label: 'Alegria', value: 'Alegria' },
      { label: 'Aloguinsan', value: 'Aloguinsan' },
      { label: 'Argao', value: 'Argao' },
      { label: 'Asturias', value: 'Asturias' },
      { label: 'Badian', value: 'Badian' },
      { label: 'Balamban', value: 'Balamban' },
      { label: 'Bantayan', value: 'Bantayan' },
      { label: 'Barili', value: 'Barili' },
      { label: 'Bogo', value: 'Bogo' },
      { label: 'Boljoon', value: 'Boljoon' },
      { label: 'Borbon', value: 'Borbon' },
      { label: 'Carcar', value: 'Carcar' },
      { label: 'Carmen', value: 'Carmen' },
      { label: 'Catmon', value: 'Catmon' },
      { label: 'Cebu City', value: 'Cebu City' },
      { label: 'Compostela', value: 'Compostela' },
      { label: 'Consolacion', value: 'Consolacion' },
      { label: 'Cordova', value: 'Cordova' },
      { label: 'Daanbantayan', value: 'Daanbantayan' },
      { label: 'Dalaguete', value: 'Dalaguete' },
      { label: 'Danao', value: 'Danao' },
      { label: 'Dumanjug', value: 'Dumanjug' },
      { label: 'Ginatilan', value: 'Ginatilan' },
      { label: 'Lapu-Lapu', value: 'Lapu-Lapu' },
      { label: 'Liloan', value: 'Liloan' },
      { label: 'Madridejos', value: 'Madridejos' },
      { label: 'Malabuyoc', value: 'Malabuyoc' },
      { label: 'Mandaue', value: 'Mandaue' },
      { label: 'Medellin', value: 'Medellin' },
      { label: 'Minglanilla', value: 'Minglanilla' },
      { label: 'Moalboal', value: 'Moalboal' },
      { label: 'Naga', value: 'Naga' },
      { label: 'Oslob', value: 'Oslob' },
      { label: 'Pilar', value: 'Pilar' },
      { label: 'Pinamungajan', value: 'Pinamungajan' },
      { label: 'Poro', value: 'Poro' },
      { label: 'Ronda', value: 'Ronda' },
      { label: 'Samboan', value: 'Samboan' },
      { label: 'San Fernando', value: 'San Fernando' },
      { label: 'San Francisco', value: 'San Francisco' },
      { label: 'San Remigio', value: 'San Remigio' },
      { label: 'Santa Fe', value: 'Santa Fe' },
      { label: 'Santander', value: 'Santander' },
      { label: 'Sibonga', value: 'Sibonga' },
      { label: 'Sogod', value: 'Sogod' },
      { label: 'Tabogon', value: 'Tabogon' },
      { label: 'Tabuelan', value: 'Tabuelan' },
      { label: 'Talisay', value: 'Talisay' },
      { label: 'Toledo', value: 'Toledo' },
      { label: 'Tuburan', value: 'Tuburan' },
      { label: 'Tudela', value: 'Tudela' }
    ]
  },
  { label: 'Davao del Norte', value: 'Davao del Norte',
    cities: [
      { label: 'Asuncion', value: 'Asuncion' },
      { label: 'Braulio E. Dujali', value: 'Braulio E. Dujali' },
      { label: 'Carmen', value: 'Carmen' },
      { label: 'Kapalong', value: 'Kapalong' },
      { label: 'New Corella', value: 'New Corella' },
      { label: 'Panabo', value: 'Panabo' },
      { label: 'Samal', value: 'Samal' },
      { label: 'San Isidro', value: 'San Isidro' },
      { label: 'Santo Tomas', value: 'Santo Tomas' },
      { label: 'Tagum', value: 'Tagum' },
      { label: 'Talaingod', value: 'Talaingod' }
    ]
  },
  { label: 'Davao del Sur', value: 'Davao del Sur',
    cities: [
      { label: 'Bansalan', value: 'Bansalan' },
      { label: 'Davao City', value: 'Davao City' },
      { label: 'Digos', value: 'Digos' },
      { label: 'Hagonoy', value: 'Hagonoy' },
      { label: 'Kiblawan', value: 'Kiblawan' },
      { label: 'Magsaysay', value: 'Magsaysay' },
      { label: 'Malalag', value: 'Malalag' },
      { label: 'Matanao', value: 'Matanao' },
      { label: 'Padada', value: 'Padada' },
      { label: 'Santa Cruz', value: 'Santa Cruz' },
      { label: 'Sulop', value: 'Sulop' }
    ]
  },
  { label: 'Davao Oriental', value: 'Davao Oriental',
    cities: [
      { label: 'Baganga', value: 'Baganga' },
      { label: 'Banaybanay', value: 'Banaybanay' },
      { label: 'Boston', value: 'Boston' },
      { label: 'Caraga', value: 'Caraga' },
      { label: 'Cateel', value: 'Cateel' },
      { label: 'Governor Generoso', value: 'Governor Generoso' },
      { label: 'Lupon', value: 'Lupon' },
      { label: 'Manay', value: 'Manay' },
      { label: 'Mati', value: 'Mati' },
      { label: 'San Isidro', value: 'San Isidro' },
      { label: 'Tarragona', value: 'Tarragona' }
    ]
  },
  { label: 'Abra', value: 'Abra',
    cities: [
      { label: 'Bangued', value: 'Bangued' },
      { label: 'Boliney', value: 'Boliney' },
      { label: 'Bucay', value: 'Bucay' },
      { label: 'Bucloc', value: 'Bucloc' },
      { label: 'Daguioman', value: 'Daguioman' },
      { label: 'Danglas', value: 'Danglas' },
      { label: 'Dolores', value: 'Dolores' },
      { label: 'La Paz', value: 'La Paz' },
      { label: 'Lacub', value: 'Lacub' },
      { label: 'Lagangilang', value: 'Lagangilang' },
      { label: 'Lagayan', value: 'Lagayan' },
      { label: 'Langiden', value: 'Langiden' },
      { label: 'Licuan-Baay', value: 'Licuan-Baay' },
      { label: 'Luba', value: 'Luba' },
      { label: 'Malibcong', value: 'Malibcong' },
      { label: 'Manabo', value: 'Manabo' },
      { label: 'Peñarrubia', value: 'Peñarrubia' },
      { label: 'Pidigan', value: 'Pidigan' },
      { label: 'Pilar', value: 'Pilar' },
      { label: 'Sallapadan', value: 'Sallapadan' },
      { label: 'San Isidro', value: 'San Isidro' },
      { label: 'San Juan', value: 'San Juan' },
      { label: 'San Quintin', value: 'San Quintin' },
      { label: 'Tayum', value: 'Tayum' },
      { label: 'Tineg', value: 'Tineg' },
      { label: 'Tubo', value: 'Tubo' },
      { label: 'Villaviciosa', value: 'Villaviciosa' }
    ]
  },
  { label: 'Agusan del Norte', value: 'Agusan del Norte',
    cities: [
      { label: 'Buenavista', value: 'Buenavista' },
      { label: 'Butuan', value: 'Butuan' },
      { label: 'Cabadbaran', value: 'Cabadbaran' },
      { label: 'Carmen', value: 'Carmen' },
      { label: 'Jabonga', value: 'Jabonga' },
      { label: 'Kitcharao', value: 'Kitcharao' },
      { label: 'Las Nieves', value: 'Las Nieves' },
      { label: 'Magallanes', value: 'Magallanes' },
      { label: 'Nasipit', value: 'Nasipit' },
      { label: 'Remedios T. Romualdez', value: 'Remedios T. Romualdez' },
      { label: 'Santiago', value: 'Santiago' },
      { label: 'Tubay', value: 'Tubay' }
    ]
  },
  { label: 'Agusan del Sur', value: 'Agusan del Sur',
    cities: [
      { label: 'Bayugan', value: 'Bayugan' },
      { label: 'Bunawan', value: 'Bunawan' },
      { label: 'Esperanza', value: 'Esperanza' },
      { label: 'La Paz', value: 'La Paz' },
      { label: 'Loreto', value: 'Loreto' },
      { label: 'Prosperidad', value: 'Prosperidad' },
      { label: 'Rosario', value: 'Rosario' },
      { label: 'San Francisco', value: 'San Francisco' },
      { label: 'San Luis', value: 'San Luis' },
      { label: 'Santa Josefa', value: 'Santa Josefa' },
      { label: 'Sibagat', value: 'Sibagat' },
      { label: 'Talacogon', value: 'Talacogon' },
      { label: 'Trento', value: 'Trento' },
      { label: 'Veruela', value: 'Veruela' }
    ]
  },
  { label: 'Aklan', value: 'Aklan',
    cities: [
      { label: 'Altavas', value: 'Altavas' },
      { label: 'Balete', value: 'Balete' },
      { label: 'Banga', value: 'Banga' },
      { label: 'Batan', value: 'Batan' },
      { label: 'Buruanga', value: 'Buruanga' },
      { label: 'Ibajay', value: 'Ibajay' },
      { label: 'Kalibo', value: 'Kalibo' },
      { label: 'Lezo', value: 'Lezo' },
      { label: 'Libacao', value: 'Libacao' },
      { label: 'Madalag', value: 'Madalag' },
      { label: 'Makato', value: 'Makato' },
      { label: 'Malay', value: 'Malay' },
      { label: 'Malinao', value: 'Malinao' },
      { label: 'Nabas', value: 'Nabas' },
      { label: 'New Washington', value: 'New Washington' },
      { label: 'Numancia', value: 'Numancia' },
      { label: 'Tangalan', value: 'Tangalan' }
    ]
  },
  { label: 'Albay', value: 'Albay',
    cities: [
      { label: 'Bacacay', value: 'Bacacay' },
      { label: 'Camalig', value: 'Camalig' },
      { label: 'Daraga', value: 'Daraga' },
      { label: 'Guinobatan', value: 'Guinobatan' },
      { label: 'Jovellar', value: 'Jovellar' },
      { label: 'Legazpi', value: 'Legazpi' },
      { label: 'Libon', value: 'Libon' },
      { label: 'Ligao', value: 'Ligao' },
      { label: 'Malilipot', value: 'Malilipot' },
      { label: 'Malinao', value: 'Malinao' },
      { label: 'Manito', value: 'Manito' },
      { label: 'Oas', value: 'Oas' },
      { label: 'Pio Duran', value: 'Pio Duran' },
      { label: 'Polangui', value: 'Polangui' },
      { label: 'Rapu-Rapu', value: 'Rapu-Rapu' },
      { label: 'Santo Domingo', value: 'Santo Domingo' },
      { label: 'Tabaco', value: 'Tabaco' },
      { label: 'Tiwi', value: 'Tiwi' }
    ]
  },
  { label: 'Antique', value: 'Antique',
    cities: [
      { label: 'Anini-y', value: 'Anini-y' },
      { label: 'Barbaza', value: 'Barbaza' },
      { label: 'Belison', value: 'Belison' },
      { label: 'Bugasong', value: 'Bugasong' },
      { label: 'Caluya', value: 'Caluya' },
      { label: 'Culasi', value: 'Culasi' },
      { label: 'Hamtic', value: 'Hamtic' },
      { label: 'Laua-an', value: 'Laua-an' },
      { label: 'Libertad', value: 'Libertad' },
      { label: 'Pandan', value: 'Pandan' },
      { label: 'Patnongon', value: 'Patnongon' },
      { label: 'San Jose de Buenavista', value: 'San Jose de Buenavista' },
      { label: 'San Remigio', value: 'San Remigio' },
      { label: 'Sebaste', value: 'Sebaste' },
      { label: 'Sibalom', value: 'Sibalom' },
      { label: 'Tibiao', value: 'Tibiao' },
      { label: 'Tobias Fornier', value: 'Tobias Fornier' },
      { label: 'Valderrama', value: 'Valderrama' }
    ]    
  },
  { label: 'Apayao', value: 'Apayao',
    cities: [
      { label: 'Calanasan', value: 'Calanasan' },
      { label: 'Conner', value: 'Conner' },
      { label: 'Flora', value: 'Flora' },
      { label: 'Kabugao', value: 'Kabugao' },
      { label: 'Luna', value: 'Luna' },
      { label: 'Pudtol', value: 'Pudtol' },
      { label: 'Santa Marcela', value: 'Santa Marcela' }
    ]    
  },
  { label: 'Aurora', value: 'Aurora',
    cities: [
      { label: 'Baler', value: 'Baler' },
      { label: 'Casiguran', value: 'Casiguran' },
      { label: 'Dilasag', value: 'Dilasag' },
      { label: 'Dinalungan', value: 'Dinalungan' },
      { label: 'Dingalan', value: 'Dingalan' },
      { label: 'Dipaculao', value: 'Dipaculao' },
      { label: 'Maria Aurora', value: 'Maria Aurora' },
      { label: 'San Luis', value: 'San Luis' }
    ]      
  },
  { label: 'Basilan', value: 'Basilan',
    cities: [
      { label: 'Akbar', value: 'Akbar' },
      { label: 'Al-Barka', value: 'Al-Barka' },
      { label: 'Hadji Mohammad Ajul', value: 'Hadji Mohammad Ajul' },
      { label: 'Hadji Muhtamad', value: 'Hadji Muhtamad' },
      { label: 'Isabela City', value: 'Isabela City' },
      { label: 'Lamitan', value: 'Lamitan' },
      { label: 'Lantawan', value: 'Lantawan' },
      { label: 'Maluso', value: 'Maluso' },
      { label: 'Sumisip', value: 'Sumisip' },
      { label: 'Tabuan-Lasa', value: 'Tabuan-Lasa' },
      { label: 'Tipo-Tipo', value: 'Tipo-Tipo' },
      { label: 'Tuburan', value: 'Tuburan' },
      { label: 'Ungkaya Pukan', value: 'Ungkaya Pukan' }
    ]       
  },
  { label: 'Bataan', value: 'Bataan',
    cities: [
      { label: 'Abucay', value: 'Abucay' },
      { label: 'Bagac', value: 'Bagac' },
      { label: 'Balanga', value: 'Balanga' },
      { label: 'Dinalupihan', value: 'Dinalupihan' },
      { label: 'Hermosa', value: 'Hermosa' },
      { label: 'Limay', value: 'Limay' },
      { label: 'Mariveles', value: 'Mariveles' },
      { label: 'Morong', value: 'Morong' },
      { label: 'Orani', value: 'Orani' },
      { label: 'Orion', value: 'Orion' },
      { label: 'Pilar', value: 'Pilar' },
      { label: 'Samal', value: 'Samal' }
    ]        
  },
  { label: 'Batanes', value: 'Batanes',
    cities: [
      { label: 'Basco', value: 'Basco' },
      { label: 'Itbayat', value: 'Itbayat' },
      { label: 'Ivana', value: 'Ivana' },
      { label: 'Mahatao', value: 'Mahatao' },
      { label: 'Sabtang', value: 'Sabtang' },
      { label: 'Uyugan', value: 'Uyugan' }
    ]           
  },
  { label: 'Batangas', value: 'Batangas',
    cities: [
      { label: 'Agoncillo', value: 'Agoncillo' },
      { label: 'Alitagtag', value: 'Alitagtag' },
      { label: 'Balayan', value: 'Balayan' },
      { label: 'Balete', value: 'Balete' },
      { label: 'Batangas City', value: 'Batangas City' },
      { label: 'Bauan', value: 'Bauan' },
      { label: 'Calaca', value: 'Calaca' },
      { label: 'Calatagan', value: 'Calatagan' },
      { label: 'Cuenca', value: 'Cuenca' },
      { label: 'Ibaan', value: 'Ibaan' },
      { label: 'Laurel', value: 'Laurel' },
      { label: 'Lemery', value: 'Lemery' },
      { label: 'Lian', value: 'Lian' },
      { label: 'Lipa', value: 'Lipa' },
      { label: 'Lobo', value: 'Lobo' },
      { label: 'Mabini', value: 'Mabini' },
      { label: 'Malvar', value: 'Malvar' },
      { label: 'Mataas na Kahoy', value: 'Mataas na Kahoy' },
      { label: 'Nasugbu', value: 'Nasugbu' },
      { label: 'Padre Garcia', value: 'Padre Garcia' },
      { label: 'Rosario', value: 'Rosario' },
      { label: 'San Jose', value: 'San Jose' },
      { label: 'San Juan', value: 'San Juan' },
      { label: 'San Luis', value: 'San Luis' },
      { label: 'San Nicolas', value: 'San Nicolas' },
      { label: 'San Pascual', value: 'San Pascual' },
      { label: 'Santa Teresita', value: 'Santa Teresita' },
      { label: 'Santo Tomas', value: 'Santo Tomas' },
      { label: 'Taal', value: 'Taal' },
      { label: 'Talisay', value: 'Talisay' },
      { label: 'Tanauan', value: 'Tanauan' },
      { label: 'Taysan', value: 'Taysan' },
      { label: 'Tingloy', value: 'Tingloy' },
      { label: 'Tuy', value: 'Tuy' }
    ]             
  },
  { label: 'Benguet', value: 'Benguet',
    cities: [
      { label: 'Atok', value: 'Atok' },
      { label: 'Baguio', value: 'Baguio' },
      { label: 'Bakun', value: 'Bakun' },
      { label: 'Bokod', value: 'Bokod' },
      { label: 'Buguias', value: 'Buguias' },
      { label: 'Itogon', value: 'Itogon' },
      { label: 'Kabayan', value: 'Kabayan' },
      { label: 'Kapangan', value: 'Kapangan' },
      { label: 'Kibungan', value: 'Kibungan' },
      { label: 'La Trinidad', value: 'La Trinidad' },
      { label: 'Mankayan', value: 'Mankayan' },
      { label: 'Sablan', value: 'Sablan' },
      { label: 'Tuba', value: 'Tuba' },
      { label: 'Tublay', value: 'Tublay' }
    ]            
  },
  { label: 'Biliran', value: 'Biliran',
    cities: [
      { label: 'Almeria', value: 'Almeria' },
      { label: 'Biliran', value: 'Biliran' },
      { label: 'Cabucgayan', value: 'Cabucgayan' },
      { label: 'Caibiran', value: 'Caibiran' },
      { label: 'Culaba', value: 'Culaba' },
      { label: 'Kawayan', value: 'Kawayan' },
      { label: 'Maripipi', value: 'Maripipi' },
      { label: 'Naval', value: 'Naval' }
    ]          
  },
  { label: 'Bohol', value: 'Bohol',
    cities: [
      { label: 'Alicia', value: 'Alicia' },
      { label: 'Anda', value: 'Anda' },
      { label: 'Batuan', value: 'Batuan' },
      { label: 'Bilar', value: 'Bilar' },
      { label: 'Candijay', value: 'Candijay' },
      { label: 'Carmen', value: 'Carmen' },
      { label: 'Dimiao', value: 'Dimiao' },
      { label: 'Duero', value: 'Duero' },
      { label: 'Garcia Hernandez', value: 'Garcia Hernandez' },
      { label: 'Guindulman', value: 'Guindulman' },
      { label: 'Jagna', value: 'Jagna' },
      { label: 'Sevilla', value: 'Sevilla' },
      { label: 'Lila', value: 'Lila' },
      { label: 'Loay', value: 'Loay' },
      { label: 'Loboc', value: 'Loboc' },
      { label: 'Mabini', value: 'Mabini' },
      { label: 'Pilar', value: 'Pilar' },
      { label: 'Sierra Bullones', value: 'Sierra Bullones' },
      { label: 'Valencia', value: 'Valencia' }
    ]            
  },
  { label: 'Bukidnon', value: 'Bukidnon',
    cities: [
      { label: 'Baungon', value: 'Baungon' },
      { label: 'Cabanglasan', value: 'Cabanglasan' },
      { label: 'Damulog', value: 'Damulog' },
      { label: 'Dangcagan', value: 'Dangcagan' },
      { label: 'Don Carlos', value: 'Don Carlos' },
      { label: 'Impasugong', value: 'Impasugong' },
      { label: 'Kadingilan', value: 'Kadingilan' },
      { label: 'Kalilangan', value: 'Kalilangan' },
      { label: 'Kibawe', value: 'Kibawe' },
      { label: 'Kitaotao', value: 'Kitaotao' },
      { label: 'Lantapan', value: 'Lantapan' },
      { label: 'Libona', value: 'Libona' },
      { label: 'Malaybalay', value: 'Malaybalay' },
      { label: 'Malitbog', value: 'Malitbog' },
      { label: 'Manolo Fortich', value: 'Manolo Fortich' },
      { label: 'Maramag', value: 'Maramag' },
      { label: 'Pangantucan', value: 'Pangantucan' },
      { label: 'Quezon', value: 'Quezon' },
      { label: 'San Fernando', value: 'San Fernando' },
      { label: 'Sumilao', value: 'Sumilao' },
      { label: 'Talakag', value: 'Talakag' },
      { label: 'Valencia', value: 'Valencia' }
    ]        
  },
  { label: 'Bulacan', value: 'Bulacan',
    cities: [
      { label: 'Angat', value: 'Angat' },
      { label: 'Balagtas', value: 'Balagtas' },
      { label: 'Baliuag', value: 'Baliuag' },
      { label: 'Bocaue', value: 'Bocaue' },
      { label: 'Bulakan', value: 'Bulakan' },
      { label: 'Bustos', value: 'Bustos' },
      { label: 'Calumpit', value: 'Calumpit' },
      { label: 'Doña Remedios Trinidad', value: 'Doña Remedios Trinidad' },
      { label: 'Guiguinto', value: 'Guiguinto' },
      { label: 'Hagonoy', value: 'Hagonoy' },
      { label: 'Malolos', value: 'Malolos' },
      { label: 'Marilao', value: 'Marilao' },
      { label: 'Meycauayan', value: 'Meycauayan' },
      { label: 'Norzagaray', value: 'Norzagaray' },
      { label: 'Obando', value: 'Obando' },
      { label: 'Pandi', value: 'Pandi' },
      { label: 'Paombong', value: 'Paombong' },
      { label: 'Plaridel', value: 'Plaridel' },
      { label: 'Pulilan', value: 'Pulilan' },
      { label: 'San Ildefonso', value: 'San Ildefonso' },
      { label: 'San Jose del Monte', value: 'San Jose del Monte' },
      { label: 'San Miguel', value: 'San Miguel' },
      { label: 'San Rafael', value: 'San Rafael' },
      { label: 'Santa Maria', value: 'Santa Maria' }
    ]            
  },
  { label: 'Cagayan', value: 'Cagayan',
    cities: [
      { label: 'Abulug', value: 'Abulug' },
      { label: 'Alcala', value: 'Alcala' },
      { label: 'Allacapan', value: 'Allacapan' },
      { label: 'Amulung', value: 'Amulung' },
      { label: 'Aparri', value: 'Aparri' },
      { label: 'Baggao', value: 'Baggao' },
      { label: 'Ballesteros', value: 'Ballesteros' },
      { label: 'Buguey', value: 'Buguey' },
      { label: 'Calayan', value: 'Calayan' },
      { label: 'Camalaniugan', value: 'Camalaniugan' },
      { label: 'Claveria', value: 'Claveria' },
      { label: 'Enrile', value: 'Enrile' },
      { label: 'Gattaran', value: 'Gattaran' },
      { label: 'Gonzaga', value: 'Gonzaga' },
      { label: 'Iguig', value: 'Iguig' },
      { label: 'Lal-lo', value: 'Lal-lo' },
      { label: 'Lasam', value: 'Lasam' },
      { label: 'Pamplona', value: 'Pamplona' },
      { label: 'Peñablanca', value: 'Peñablanca' },
      { label: 'Piat', value: 'Piat' },
      { label: 'Rizal', value: 'Rizal' },
      { label: 'Sanchez-Mira', value: 'Sanchez-Mira' },
      { label: 'Santa Ana', value: 'Santa Ana' },
      { label: 'Santa Praxedes', value: 'Santa Praxedes' },
      { label: 'Santa Teresita', value: 'Santa Teresita' },
      { label: 'Santo Niño', value: 'Santo Niño' },
      { label: 'Solana', value: 'Solana' },
      { label: 'Tuao', value: 'Tuao' },
      { label: 'Tuguegarao City', value: 'Tuguegarao City' }
    ]               
  },
  { label: 'Camarines Norte', value: 'Camarines Norte',
    cities: [
      { label: 'Basud', value: 'Basud' },
      { label: 'Capalonga', value: 'Capalonga' },
      { label: 'Daet', value: 'Daet' },
      { label: 'Jose Panganiban', value: 'Jose Panganiban' },
      { label: 'Labo', value: 'Labo' },
      { label: 'Mercedes', value: 'Mercedes' },
      { label: 'Paracale', value: 'Paracale' },
      { label: 'San Lorenzo Ruiz', value: 'San Lorenzo Ruiz' },
      { label: 'San Vicente', value: 'San Vicente' },
      { label: 'Santa Elena', value: 'Santa Elena' },
      { label: 'Talisay', value: 'Talisay' },
      { label: 'Vinzons', value: 'Vinzons' }
    ]                 
  },
  { label: 'Camarines Sur', value: 'Camarines Sur',
    cities: [
      { label: 'Baao', value: 'Baao' },
      { label: 'Balatan', value: 'Balatan' },
      { label: 'Bato', value: 'Bato' },
      { label: 'Bombon', value: 'Bombon' },
      { label: 'Buhi', value: 'Buhi' },
      { label: 'Bula', value: 'Bula' },
      { label: 'Cabusao', value: 'Cabusao' },
      { label: 'Calabanga', value: 'Calabanga' },
      { label: 'Camaligan', value: 'Camaligan' },
      { label: 'Canaman', value: 'Canaman' },
      { label: 'Caramoan', value: 'Caramoan' },
      { label: 'Del Gallego', value: 'Del Gallego' },
      { label: 'Gainza', value: 'Gainza' },
      { label: 'Garchitorena', value: 'Garchitorena' },
      { label: 'Goa', value: 'Goa' },
      { label: 'Iriga', value: 'Iriga' },
      { label: 'Lagonoy', value: 'Lagonoy' },
      { label: 'Libmanan', value: 'Libmanan' },
      { label: 'Lupi', value: 'Lupi' },
      { label: 'Magarao', value: 'Magarao' },
      { label: 'Milaor', value: 'Milaor' },
      { label: 'Minalabac', value: 'Minalabac' },
      { label: 'Nabua', value: 'Nabua' },
      { label: 'Naga', value: 'Naga' },
      { label: 'Ocampo', value: 'Ocampo' },
      { label: 'Pamplona', value: 'Pamplona' },
      { label: 'Pasacao', value: 'Pasacao' },
      { label: 'Pili', value: 'Pili' },
      { label: 'Presentacion', value: 'Presentacion' },
      { label: 'Ragay', value: 'Ragay' },
      { label: 'Sagñay', value: 'Sagñay' },
      { label: 'San Fernando', value: 'San Fernando' },
      { label: 'San Jose', value: 'San Jose' },
      { label: 'Sipocot', value: 'Sipocot' },
      { label: 'Siruma', value: 'Siruma' },
      { label: 'Tigaon', value: 'Tigaon' },
      { label: 'Tinambac', value: 'Tinambac' }
    ]                   
  },
  { label: 'Camiguin', value: 'Camiguin',
    cities: [
      { label: 'Catarman', value: 'Catarman' },
      { label: 'Guinsiliban', value: 'Guinsiliban' },
      { label: 'Mahinog', value: 'Mahinog' },
      { label: 'Mambajao', value: 'Mambajao' },
      { label: 'Sagay', value: 'Sagay' }
    ]               
  },
]





export const provinces = {
    Capiz: [
      'Cuartero',
      'Dao',
      'Dumalag',
      'Dumarao',
      'Ivisan',
      'Jamindan',
      'Maayon',
      'Mambusao',
      'Panay',
      'Panitan',
      'Pilar',
      'Pontevedra',
      'President Roxas',
      'Roxas City',
      'Sapian',
      'Sigma',
      'Tapaz',
    ],
    Catanduanes: [
      'Bagamanoc',
      'Baras',
      'Bato',
      'Caramoran',
      'Gigmoto',
      'Pandan',
      'Panganiban',
      'San Andres',
      'San Miguel',
      'Viga',
      'Virac',
    ],
    Cavite: [
      'Alfonso',
      'Amadeo',
      'Bacoor',
      'Carmona',
      'Cavite City',
      'Dasmariñas',
      'General Emilio Aguinaldo',
      'General Mariano Alvarez',
      'General Trias',
      'Imus',
      'Indang',
      'Kawit',
      'Magallanes',
      'Maragondon',
      'Mendez',
      'Naic',
      'Noveleta',
      'Rosario',
      'Silang',
      'Tagaytay',
      'Tanza',
      'Ternate',
      'Trece Martires',
    ],
    'Compostela Valley': [
      'Compostela',
      'Laak',
      'Mabini',
      'Maco',
      'Maragusan',
      'Mawab',
      'Monkayo',
      'Montevista',
      'Nabunturan',
      'New Bataan',
      'Pantukan',
    ],
    Cotabato: [
      'Alamada',
      'Aleosan',
      'Antipas',
      'Arakan',
      'Banisilan',
      'Carmen',
      'Kabacan',
      'Kidapawan',
      'Libungan',
      "M'lang",
      'Magpet',
      'Makilala',
      'Matalam',
      'Midsayap',
      'Pigcawayan',
      'Pikit',
      'President Roxas',
      'Tulunan',
    ],
    'Dinagat Islands': [
      'Basilisa',
      'Cagdianao',
      'Dinagat',
      'Libjo',
      'Loreto',
      'San Jose',
      'Tubajon',
    ],
    'Eastern Samar': [
      'Arteche',
      'Balangiga',
      'Balangkayan',
      'Borongan',
      'Can-avid',
      'Dolores',
      'General MacArthur',
      'Giporlos',
      'Guiuan',
      'Hernani',
      'Jipapad',
      'Lawaan',
      'Llorente',
      'Maslog',
      'Maydolong',
      'Mercedes',
      'Oras',
      'Quinapondan',
      'Salcedo',
      'San Julian',
      'San Policarpo',
      'Sulat',
      'Taft',
    ],
    Guimaras: [
      'Buenavista',
      'Jordan',
      'Nueva Valencia',
      'San Lorenzo',
      'Sibunag',
    ],
    Ifugao: [
      'Aguinaldo',
      'Alfonso Lista',
      'Asipulo',
      'Banaue',
      'Hingyon',
      'Hungduan',
      'Kiangan',
      'Lagawe',
      'Lamut',
      'Mayoyao',
      'Tinoc',
    ],
    'Ilocos Norte': [
      'Adams',
      'Bacarra',
      'Badoc',
      'Bangui',
      'Banna',
      'Batac',
      'Burgos',
      'Carasi',
      'Currimao',
      'Dingras',
      'Dumalneg',
      'Laoag',
      'Marcos',
      'Nueva Era',
      'Pagudpud',
      'Paoay',
      'Pasuquin',
      'Piddig',
      'Pinili',
      'San Nicolas',
      'Sarrat',
      'Solsona',
      'Vintar',
    ],
    'Ilocos Sur': [
      'Alilem',
      'Banayoyo',
      'Bantay',
      'Burgos',
      'Cabugao',
      'Candon',
      'Caoayan',
      'Cervantes',
      'Galimuyod',
      'Gregorio del Pilar',
      'Lidlidda',
      'Magsingal',
      'Nagbukel',
      'Narvacan',
      'Quirino',
      'Salcedo',
      'San Emilio',
      'San Esteban',
      'San Ildefonso',
      'San Juan',
      'San Vicente',
      'Santa',
      'Santa Catalina',
      'Santa Cruz',
      'Santa Lucia',
      'Santa Maria',
      'Santiago',
      'Santo Domingo',
      'Sigay',
      'Sinait',
      'Sugpon',
      'Suyo',
      'Tagudin',
      'Vigan',
    ],
    Iloilo: [
      'Ajuy',
      'Alimodian',
      'Anilao',
      'Badiangan',
      'Balasan',
      'Banate',
      'Barotac Nuevo',
      'Barotac Viejo',
      'Batad',
      'Bingawan',
      'Cabatuan',
      'Calinog',
      'Carles',
      'Concepcion',
      'Dingle',
      'Dueñas',
      'Dumangas',
      'Estancia',
      'Guimbal',
      'Igbaras',
      'Iloilo City',
      'Janiuay',
      'Lambunao',
      'Leganes',
      'Lemery',
      'Leon',
      'Maasin',
      'Miagao',
      'Mina',
      'New Lucena',
      'Oton',
      'Passi',
      'Pavia',
      'Pototan',
      'San Dionisio',
      'San Enrique',
      'San Joaquin',
      'San Miguel',
      'San Rafael',
      'Santa Barbara',
      'Sara',
      'Tigbauan',
      'Tubungan',
      'Zarraga',
    ],
    Isabela: [
      'Alicia',
      'Angadanan',
      'Aurora',
      'Benito Soliven',
      'Burgos',
      'Cabagan',
      'Cabatuan',
      'Cauayan',
      'Cordon',
      'Delfin Albano',
      'Dinapigue',
      'Divilacan',
      'Echague',
      'Gamu',
      'Ilagan',
      'Jones',
      'Luna',
      'Maconacon',
      'Mallig',
      'Naguilian',
      'Palanan',
      'Quezon',
      'Quirino',
      'Ramon',
      'Reina Mercedes',
      'Roxas',
      'San Agustin',
      'San Guillermo',
      'San Isidro',
      'San Manuel',
      'San Mariano',
      'San Mateo',
      'San Pablo',
      'Santa Maria',
      'Santiago',
      'Santo Tomas',
      'Tumauini',
    ],
    Kalinga: [
      'Balbalan',
      'Lubuagan',
      'Pasil',
      'Pinukpuk',
      'Rizal',
      'Tabuk',
      'Tanudan',
      'Tinglayan',
    ],
    'La Union': [
      'Agoo',
      'Aringay',
      'Bacnotan',
      'Bagulin',
      'Balaoan',
      'Bangar',
      'Bauang',
      'Burgos',
      'Caba',
      'Luna',
      'Naguilian',
      'Pugo',
      'Rosario',
      'San Fernando',
      'San Gabriel',
      'San Juan',
      'Santo Tomas',
      'Santol',
      'Sudipen',
      'Tubao',
    ],
    Laguna: [
      'Alaminos',
      'Bay',
      'Biñan',
      'Cabuyao',
      'Calamba',
      'Calauan',
      'Cavinti',
      'Famy',
      'Kalayaan',
      'Liliw',
      'Los Baños',
      'Luisiana',
      'Lumban',
      'Mabitac',
      'Magdalena',
      'Majayjay',
      'Nagcarlan',
      'Paete',
      'Pagsanjan',
      'Pakil',
      'Pangil',
      'Pila',
      'Rizal',
      'San Pablo',
      'San Pedro',
      'Santa Cruz',
      'Santa Maria',
      'Santa Rosa',
      'Siniloan',
      'Victoria',
    ],
    'Lanao del Norte': [
      'Bacolod',
      'Baloi',
      'Baroy',
      'Iligan',
      'Kapatagan',
      'Kauswagan',
      'Kolambugan',
      'Lala',
      'Linamon',
      'Magsaysay',
      'Maigo',
      'Matungao',
      'Munai',
      'Nunungan',
      'Pantao Ragat',
      'Pantar',
      'Poona Piagapo',
      'Salvador',
      'Sapad',
      'Sultan Naga Dimaporo',
      'Tagoloan',
      'Tangcal',
      'Tubod',
    ],
    'Lanao del Sur': [
      'Amai Manabilang',
      'Bacolod-Kalawi',
      'Balabagan',
      'Balindong',
      'Bayang',
      'Binidayan',
      'Buadiposo-Buntong',
      'Bubong',
      'Butig',
      'Calanogas',
      'Ditsaan-Ramain',
      'Ganassi',
      'Kapai',
      'Kapatagan',
      'Lumba-Bayabao',
      'Lumbaca-Unayan',
      'Lumbatan',
      'Lumbayanague',
      'Madalum',
      'Madamba',
      'Maguing',
      'Malabang',
      'Marantao',
      'Marawi',
      'Marogong',
      'Masiu',
      'Mulondo',
      'Pagayawan',
      'Piagapo',
      'Picong',
      'Poona Bayabao',
      'Pualas',
      'Saguiaran',
      'Sultan Dumalondong',
      'Tagoloan II',
      'Tamparan',
      'Taraka',
      'Tubaran',
      'Tugaya',
      'Wao',
    ],
    Leyte: [
      'Abuyog',
      'Alangalang',
      'Albuera',
      'Babatngon',
      'Barugo',
      'Bato',
      'Baybay',
      'Burauen',
      'Calubian',
      'Capoocan',
      'Carigara',
      'Dagami',
      'Dulag',
      'Hilongos',
      'Hindang',
      'Inopacan',
      'Isabel',
      'Jaro',
      'Javier',
      'Julita',
      'Kananga',
      'La Paz',
      'Leyte',
      'MacArthur',
      'Mahaplag',
      'Matag-ob',
      'Matalom',
      'Mayorga',
      'Merida',
      'Ormoc',
      'Palo',
      'Palompon',
      'Pastrana',
      'San Isidro',
      'San Miguel',
      'Santa Fe',
      'Tabango',
      'Tabontabon',
      'Tacloban',
      'Tanauan',
      'Tolosa',
      'Tunga',
      'Villaba',
    ],
    Maguindanao: [
      'Barira',
      'Buldon',
      'Datu Anggal Midtimbang',
      'Datu Blah T. Sinsuat',
      'Datu Odin Sinsuat',
      'Kabuntalan',
      'Matanog',
      'Northern Kabuntalan',
      'Parang',
      'Sultan Kudarat',
      'Sultan Mastura',
      'Sultan Sumagka',
      'Upi',
    ],
    Marinduque: [
      'Boac',
      'Buenavista',
      'Gasan',
      'Mogpog',
      'Santa Cruz',
      'Torrijos',
    ],
    Masbate: [
      'Aroroy',
      'Baleno',
      'Balud',
      'Batuan',
      'Cataingan',
      'Cawayan',
      'Claveria',
      'Dimasalang',
      'Esperanza',
      'Mandaon',
      'Masbate City',
      'Milagros',
      'Mobo',
      'Monreal',
      'Palanas',
      'Pio V. Corpuz',
      'Placer',
      'San Fernando',
      'San Jacinto',
      'San Pascual',
      'Uson',
    ],
    'Misamis Occidental': [
      'Aloran',
      'Baliangao',
      'Bonifacio',
      'Calamba',
      'Clarin',
      'Concepcion',
      'Don Victoriano Chiongbian',
      'Jimenez',
      'Lopez Jaena',
      'Oroquieta',
      'Ozamiz',
      'Panaon',
      'Plaridel',
      'Sapang Dalaga',
      'Sinacaban',
      'Tangub',
      'Tudela',
    ],
    'Misamis Oriental': [
      'Alubijid',
      'Balingasag',
      'Balingoan',
      'Binuangan',
      'Cagayan de Oro',
      'Claveria',
      'El Salvador',
      'Gingoog',
      'Gitagum',
      'Initao',
      'Jasaan',
      'Kinoguitan',
      'Lagonglong',
      'Laguindingan',
      'Libertad',
      'Lugait',
      'Magsaysay',
      'Manticao',
      'Medina',
      'Naawan',
      'Opol',
      'Salay',
      'Sugbongcogon',
      'Tagoloan',
      'Talisayan',
      'Villanueva',
    ],
    'Mountain Province': [
      'Barlig',
      'Bauko',
      'Besao',
      'Bontoc',
      'Natonin',
      'Paracelis',
      'Sabangan',
      'Sadanga',
      'Sagada',
      'Tadian',
    ],
    'Negros Occidental': [
      'Bacolod',
      'Bago',
      'Binalbagan',
      'Cadiz',
      'Calatrava',
      'Candoni',
      'Cauayan',
      'Enrique B. Magalona',
      'Escalante',
      'Himamaylan',
      'Hinigaran',
      'Hinoba-an',
      'Ilog',
      'Isabela',
      'Kabankalan',
      'La Carlota',
      'La Castellana',
      'Manapla',
      'Moises Padilla',
      'Murcia',
      'Pontevedra',
      'Pulupandan',
      'Sagay',
      'Salvador Benedicto',
      'San Carlos',
      'San Enrique',
      'Silay',
      'Sipalay',
      'Talisay',
      'Toboso',
      'Valladolid',
      'Victorias',
    ],
    'Negros Oriental': [
      'Amlan',
      'Ayungon',
      'Bacong',
      'Bais',
      'Basay',
      'Bayawan',
      'Bindoy',
      'Canlaon',
      'Dauin',
      'Dumaguete',
      'Guihulngan',
      'Jimalalud',
      'La Libertad',
      'Mabinay',
      'Manjuyod',
      'Pamplona',
      'San Jose',
      'Santa Catalina',
      'Siaton',
      'Sibulan',
      'Tanjay',
      'Tayasan',
      'Valencia',
      'Vallehermoso',
      'Zamboanguita',
    ],
    'Northern Samar': [
      'Allen',
      'Biri',
      'Bobon',
      'Capul',
      'Catarman',
      'Catubig',
      'Gamay',
      'Laoang',
      'Lapinig',
      'Las Navas',
      'Lavezares',
      'Lope de Vega',
      'Mapanas',
      'Mondragon',
      'Palapag',
      'Pambujan',
      'Rosario',
      'San Antonio',
      'San Isidro',
      'San Jose',
      'San Roque',
      'San Vicente',
      'Silvino Lobos',
      'Victoria',
    ],
    'Nueva Ecija': [
      'Aliaga',
      'Bongabon',
      'Cabanatuan',
      'Cabiao',
      'Carranglan',
      'Cuyapo',
      'Gabaldon',
      'Gapan',
      'General Mamerto Natividad',
      'General Tinio',
      'Guimba',
      'Jaen',
      'Laur',
      'Licab',
      'Llanera',
      'Lupao',
      'Muñoz',
      'Nampicuan',
      'Palayan',
      'Pantabangan',
      'Peñaranda',
      'Quezon',
      'Rizal',
      'San Antonio',
      'San Isidro',
      'Cabaritan',
      'San Leonardo',
      'Santa Rosa',
      'Santo Domingo',
      'Talavera',
      'Talugtug',
      'Zaragoza',
    ],
    'Nueva Vizcaya': [
      'Alfonso Castañeda',
      'Ambaguio',
      'Aritao',
      'Bagabag',
      'Bambang',
      'Bayombong',
      'Diadi',
      'Dupax del Norte',
      'Dupax del Sur',
      'Kasibu',
      'Kayapa',
      'Quezon',
      'Santa Fe',
      'Solano',
      'Villaverde',
    ],
    'Occidental Mindoro': [
      'Abra de Ilog',
      'Calintaan',
      'Looc',
      'Lubang',
      'Magsaysay',
      'Mamburao',
      'Paluan',
      'Rizal',
      'Sablayan',
      'San Jose',
      'Santa Cruz',
    ],
    'Oriental Mindoro': [
      'Baco',
      'Bansud',
      'Bongabong',
      'Bulalacao',
      'Calapan',
      'Gloria',
      'Mansalay',
      'Naujan',
      'Pinamalayan',
      'Pola',
      'Puerto Galera',
      'Roxas',
      'San Teodoro',
      'Socorro',
      'Victoria',
    ],
    Palawan: [
      'Aborlan',
      'Agutaya',
      'Araceli',
      'Balabac',
      'Bataraza',
      "Brooke's Point",
      'Busuanga',
      'Cagayancillo',
      'Coron',
      'Culion',
      'Cuyo',
      'Dumaran',
      'El Nido',
      'Kalayaan',
      'Linapacan',
      'Magsaysay',
      'Narra',
      'Puerto Princesa',
      'Quezon',
      'Rizal',
      'Roxas',
      'San Vicente',
      'Sofronio Española',
      'Taytay',
    ],
    Pampanga: [
      'Angeles',
      'Apalit',
      'Arayat',
      'Bacolor',
      'Candaba',
      'Floridablanca',
      'Guagua',
      'Lubao',
      'Mabalacat',
      'Macabebe',
      'Magalang',
      'Masantol',
      'Mexico',
      'Minalin',
      'Porac',
      'San Fernando',
      'San Luis',
      'San Simon',
      'Santa Ana',
      'Santa Rita',
      'Santo Tomas',
      'Sasmuan',
    ],
    Pangasinan: [
      'Agno',
      'Aguilar',
      'Alaminos',
      'Alcala',
      'Anda',
      'Asingan',
      'Balungao',
      'Bani',
      'Basista',
      'Bautista',
      'Bayambang',
      'Binalonan',
      'Binmaley',
      'Bolinao',
      'Bugallon',
      'Burgos',
      'Calasiao',
      'Dasol',
      'Dagupan',
      'Dasol',
      'Infanta',
      'Labrador',
      'Laoac',
      'Lingayen',
      'Mabini',
      'Malasiqui',
      'Manaoag',
      'Mangaldan',
      'Mangatarem',
      'Mapandan',
      'Natividad',
      'Pozorrubio',
      'Rosales',
      'San Carlos',
      'San Fabian',
      'San Jacinto',
      'San Manuel',
      'San Nicolas',
      'San Quintin',
      'Santa Barbara',
      'Santa Maria',
      'Santo Tomas',
      'Sison',
      'Sual',
      'Tayug',
      'Umingan',
      'Urbiztondo',
      'Urdaneta',
      'Villasis',
    ],
    Quezon: [
      'Agdangan',
      'Alabat',
      'Atimonan',
      'Buenavista',
      'Burdeos',
      'Calauag',
      'Candelaria',
      'Catanauan',
      'Dolores',
      'General Luna',
      'General Nakar',
      'Guinayangan',
      'Gumaca',
      'Infanta',
      'Jomalig',
      'Lopez',
      'Lucban',
      'Lucena',
      'Macalelon',
      'Mauban',
      'Mulanay',
      'Padre Burgos',
      'Pagbilao',
      'Panukulan',
      'Patnanungan',
      'Perez',
      'Pitogo',
      'Plaridel',
      'Polillo',
      'Quezon',
      'Real',
      'Sampaloc',
      'San Andres',
      'San Antonio',
      'San Francisco',
      'San Narciso',
      'Sariaya',
      'Tagkawayan',
      'Tayabas',
      'Tiaong',
      'Unisan',
    ],
    Quirino: [
      'Aglipay',
      'Cabarroguis',
      'Diffun',
      'Maddela',
      'Nagtipunan',
      'Saguday',
    ],
    Rizal: [
      'Angono',
      'Antipolo',
      'Baras',
      'Binangonan',
      'Cainta',
      'Cardona',
      'Jalajala',
      'Morong',
      'Pililla',
      'Rodriguez',
      'San Mateo',
      'Tanay',
      'Taytay',
      'Teresa',
    ],
    Romblon: [
      'Alcantara',
      'Banton',
      'Cajidiocan',
      'Calatrava',
      'Concepcion',
      'Corcuera',
      'Ferrol',
      'Looc',
      'Magdiwang',
      'Odiongan',
      'Romblon',
      'San Agustin',
      'San Andres',
      'San Fernando',
      'San Jose',
      'Santa Fe',
      'Santa Maria',
    ],
    Samar: [
      'Almagro',
      'Basey',
      'Calbayog',
      'Calbiga',
      'Catbalogan',
      'Daram',
      'Gandara',
      'Hinabangan',
      'Jiabong',
      'Marabut',
      'Matuguinao',
      'Motiong',
      'Pagsanghan',
      'Paranas',
      'Pinabacdao',
      'San Jorge',
      'San Jose de Buan',
      'San Sebastian',
      'Santa Margarita',
      'Santa Rita',
      'Santo Niño',
      'Tagapul-an',
      'Talalora',
      'Tarangnan',
      'Villareal',
      'Zumarraga',
    ],
    Sarangani: [
      'Alabel',
      'Glan',
      'Kiamba',
      'Maasim',
      'Maitum',
      'Malapatan',
      'Malungon',
    ],
    'Shariff Kabunsuan': [
      'Barira',
      'Buldon',
      'Datu Blah T. Sinsuat',
      'Datu Odin Sinsuat',
      'Kabuntalan',
      'Matanog',
      'Northern Kabuntalan',
      'Parang',
      'Sultan Kudarat',
      'Sultan Mastura',
      'Upi',
    ],
    Siquijor: [
      'Enrique Villanueva',
      'Larena',
      'Lazi',
      'Maria',
      'San Juan',
      'Siquijor',
    ],
    Sorsogon: [
      'Barcelona',
      'Bulan',
      'Bulusan',
      'Casiguran',
      'Castilla',
      'Donsol',
      'Gubat',
      'Irosin',
      'Juban',
      'Magallanes',
      'Matnog',
      'Pilar',
      'Prieto Diaz',
      'Santa Magdalena',
      'Sorsogon City',
    ],
    'South Cotabato': [
      'Banga',
      'General Santos',
      'Koronadal',
      'Lake Sebu',
      'Norala',
      'Polomolok',
      'Santo Niño',
      'Surallah',
      "T'Boli",
      'Tampakan',
      'Tantangan',
      'Tupi',
    ],
    'Southern Leyte': [
      'Anahawan',
      'Bontoc',
      'Hinunangan',
      'Hinundayan',
      'Libagon',
      'Liloan',
      'Limasawa',
      'Maasin',
      'Macrohon',
      'Malitbog',
      'Padre Burgos',
      'Pintuyan',
      'Saint Bernard',
      'San Francisco',
      'San Juan',
      'San Ricardo',
      'Silago',
      'Sogod',
      'Tomas Oppus',
    ],
    'Sultan Kudarat': [
      'Bagumbayan',
      'Columbio',
      'Esperanza',
      'Isulan',
      'Kalamansig',
      'Lambayong',
      'Lebak',
      'Lutayan',
      'Palimbang',
      'President Quirino',
      'Senator Ninoy Aquino',
      'Tacurong',
    ],
    Sulu: [
      'Banguingui',
      'Hadji Panglima Tahil',
      'Indanan',
      'Jolo',
      'Kalingalan Caluang',
      'Lugus',
      'Luuk',
      'Maimbung',
      'Old Panamao',
      'Omar',
      'Pandami',
      'Panglima Estino',
      'Pangutaran',
      'Parang',
      'Pata',
      'Patikul',
      'Siasi',
      'Talipao',
      'Tapul',
    ],
    'Surigao del Norte': [
      'Alegria',
      'Bacuag',
      'Burgos',
      'Claver',
      'Dapa',
      'Del Carmen',
      'General Luna',
      'Gigaquit',
      'Mainit',
      'Malimono',
      'Pilar',
      'Placer',
      'San Benito',
      'San Francisco',
      'San Isidro',
      'Santa Monica',
      'Sison',
      'Socorro',
      'Surigao City',
      'Tagana-an',
      'Tubod',
    ],
    'Surigao del Sur': [
      'Barobo',
      'Bayabas',
      'Bislig',
      'Cagwait',
      'Cantilan',
      'Carmen',
      'Carrascal',
      'Cortes',
      'Hinatuan',
      'Lanuza',
      'Lianga',
      'Lingig',
      'Madrid',
      'Marihatag',
      'San Agustin',
      'San Miguel',
      'Tagbina',
      'Tago',
      'Tandag',
    ],
    Tarlac: [
      'Anao',
      'Bamban',
      'Camiling',
      'Capas',
      'Concepcion',
      'Gerona',
      'La Paz',
      'Mayantoc',
      'Moncada',
      'Paniqui',
      'Pura',
      'Ramos',
      'San Clemente',
      'San Jose',
      'San Manuel',
      'Santa Ignacia',
      'Tarlac City',
      'Victoria',
    ],
    'Tawi-Tawi': [
      'Bongao',
      'Languyan',
      'Mapun',
      'Panglima Sugala',
      'Sapa-Sapa',
      'Sibutu',
      'Simunul',
      'Sitangkai',
      'South Ubian',
      'Tandubas',
      'Turtle Islands',
    ],
    Zambales: [
      'Botolan',
      'Cabangan',
      'Candelaria',
      'Iba',
      'Masinloc',
      'Olongapo',
      'Palauig',
      'San Antonio',
      'San Felipe',
      'San Marcelino',
      'San Narciso',
      'Santa Cruz',
      'Subic',
    ],
    'Zamboanga del Norte': [
      'Baliguian',
      'Dapitan',
      'Dipolog',
      'Godod',
      'Gutalac',
      'Jose Dalman',
      'Kalawit',
      'Katipunan',
      'La Libertad',
      'Labason',
      'Leon B. Postigo',
      'Liloy',
      'Manukan',
      'Mutia',
      'Piñan',
      'Polanco',
      'President Manuel A. Roxas',
      'Rizal',
      'Salug',
      'Sergio Osmeña Sr.',
      'Siayan',
      'Sibuco',
      'Sibutad',
      'Sindangan',
      'Siocon',
      'Sirawai',
      'Tampilisan',
    ],
    'Zamboanga del Sur': [
      'Aurora',
      'Bayog',
      'Dimataling',
      'Dinas',
      'Dumalinao',
      'Dumingag',
      'Guipos',
      'Josefina',
      'Kumalarang',
      'Labangan',
      'Lakewood',
      'Lapuyan',
      'Mahayag',
      'Margosatubig',
      'Midsalip',
      'Molave',
      'Pagadian',
      'Pitogo',
      'Ramon Magsaysay',
      'San Miguel',
      'San Pablo',
      'Sominot',
      'Tabina',
      'Tambulig',
      'Tigbao',
      'Tukuran',
      'Vincenzo A. Sagun',
      'Zamboanga City',
    ],
    'Zamboanga Sibugay': [
      'Alicia',
      'Buug',
      'Diplahan',
      'Imelda',
      'Ipil',
      'Kabasalan',
      'Mabuhay',
      'Malangas',
      'Naga',
      'Olutanga',
      'Payao',
      'Roseller Lim',
      'Siay',
      'Talusan',
      'Titay',
      'Tungawan',
    ],
};